/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkdemo_MyJNIClass */

#ifndef _Included_com_example_ndkdemo_MyJNIClass
#define _Included_com_example_ndkdemo_MyJNIClass
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
